spring:
  application:
    name: smart-campus-backend
  config:
    import: optional:file:./.env[.properties]
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017}
      database: ${MONGODB_DATABASE:smart_campus_db}

server:
  port: ${SERVER_PORT:5000}

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000}
